version: "3.5"
services:
  app:
    container_name: appUsers
    image: appusers
    command: bash -c 'python manage.py makemigrations mysite & python manage.py migrate & python manage.py runserver 0.0.0.0:8000'
    restart: always
    build: .
    ports:
      - "8000:8000"
    tty: true
networks:
  default:
    external:
      name: mongodb
