version: "2"
services:
  app:
    container_name: app3
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
    tty: true
  mongo:
    container_name: mongo3
    image: mongo
    ports:
      - "27017:27017"